// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk7y4Oc6nRTqab6syefoxWx7ssRixWM_A',
    appId: '1:1027982307619:android:4a499fa08e93a3ecd15c96',
    messagingSenderId: '1027982307619',
    projectId: 'barter-864e8',
    storageBucket: 'barter-864e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzQ9JJfTtQ9k3xo6sdrCUpA4omHCyfbfU',
    appId: '1:1027982307619:ios:e97bc91ea1191735d15c96',
    messagingSenderId: '1027982307619',
    projectId: 'barter-864e8',
    storageBucket: 'barter-864e8.firebasestorage.app',
    androidClientId: '1027982307619-qk9thkjtf0dhov3ir500pnf1m8li9i4p.apps.googleusercontent.com',
    iosClientId: '1027982307619-96johsu3ubniul9jmbm5qcsc44s27b3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.barter',
  );
}
